services:
  polya_bot:
    # Указывает Docker Compose, что нужно искать Dockerfile 
    # в текущей директории, где расположен этот YAML-файл.
    build: .
    
    # Задаёт фиксированное имя контейнера для удобства управления логами и оболочкой (shell)
    container_name: polya_bot
    
    # Обеспечивает перезапуск контейнера в случае его сбоя, гарантируя работу 24/7.
    restart: always
    
    # Использует файл .env (который должен лежать рядом с этим файлом) для загрузки переменных.
    env_file: .env
    
    # Настройка переменных окружения:
    # Мы явно назначаем значение из переменной BOT_TOKEN, найденной в .env,
    # внутренней переменной BOT_TOKEN внутри контейнера.
    environment:
      BOT_TOKEN: ${BOT_TOKEN} 
      
    # Команда запуска берется из Dockerfile, что является лучшей практикой.
    # Если вы хотите принудительно запустить другой скрипт, используйте command:
    # command: python main.py
