version: "3.9"

services:
  polya_bot:
    build: 
      context: ./polya-bot 
      dockerfile: Dockerfile
    
    container_name: polya_bot
    restart: always
    
    environment:
      BOT_TOKEN: ${BOT_TOKEN} 

    env_file: .env